/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xgs.zwy.util;

import com.xgs.zwy.constant.Constants;
import com.xgs.zwy.vo.Item;

/**
 *
 * @author n-194
 */
public class CDHeadPanel extends javax.swing.JPanel {

    /**
     * Creates new form CDHeadPanel
     */
    public CDHeadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        billNO_Label = new javax.swing.JLabel();
        billNO_TextField = new javax.swing.JTextField();
        voyageName_Label = new javax.swing.JLabel();
        voyageName_TextField = new javax.swing.JTextField();
        i_E_Flag_Label = new javax.swing.JLabel();
        i_E_Flag_ComboBox = new javax.swing.JComboBox();
        totalCount_Label = new javax.swing.JLabel();
        totalCount_TextField = new javax.swing.JTextField();
        totalWT_Label = new javax.swing.JLabel();
        totalWT_TextField = new javax.swing.JTextField();
        i_E_Date_Label = new javax.swing.JLabel();
        i_E_Date_mp = new javax.swing.JTextField();
        i_E_Port_Label = new javax.swing.JLabel();
        i_E_Port_TextField = new javax.swing.JTextField();
        destinationPort_Label = new javax.swing.JLabel();
        destinationPort_TextField = new javax.swing.JTextField();
        trafMode_Label = new javax.swing.JLabel();
        trafMode_ComboBox = new javax.swing.JComboBox();
        dialog_Button3 = new javax.swing.JButton();
        dialog_Button4 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "舱单"));

        billNO_Label.setText("总运单号：");


        voyageName_Label.setText("运输工具名称：");


        i_E_Flag_Label.setText("进出口标示：");

        Item<String, String>[] i_e_Flag = ConstantUtils.map2Array(
				Constants.I_E_FLAG, true);
		i_E_Flag_ComboBox
				.setModel(new javax.swing.DefaultComboBoxModel(i_e_Flag));

        totalCount_Label.setText("主单件数：");


        totalWT_Label.setText("主单重量：");


        i_E_Date_Label.setText("进出港日期：");


        i_E_Port_Label.setText("进出口岸代码：");


        destinationPort_Label.setText("起运港/抵运港：");


        trafMode_Label.setText("运输方式：");

        Item<String, String>[] trafModes = ConstantUtils.map2Array(
				Constants.TRAFMODE, false);
		trafMode_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				trafModes));
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trafMode_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destinationPort_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_Port_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_Date_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalWT_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalCount_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_Flag_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voyageName_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billNO_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billNO_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(voyageName_TextField)
                    .addComponent(totalCount_TextField)
                    .addComponent(i_E_Flag_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalWT_TextField)
                    .addComponent(i_E_Date_mp)
                    .addComponent(i_E_Port_TextField)
                    .addComponent(destinationPort_TextField)
                    .addComponent(trafMode_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billNO_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billNO_Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voyageName_Label)
                    .addComponent(voyageName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(i_E_Flag_Label)
                    .addComponent(i_E_Flag_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCount_Label)
                    .addComponent(totalCount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalWT_Label)
                    .addComponent(totalWT_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i_E_Date_Label)
                    .addComponent(i_E_Date_mp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i_E_Port_Label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(i_E_Port_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationPort_Label)
                    .addComponent(destinationPort_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trafMode_Label)
                    .addComponent(trafMode_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {billNO_Label, billNO_TextField, destinationPort_Label, destinationPort_TextField, i_E_Date_Label, i_E_Date_mp, i_E_Flag_ComboBox, i_E_Flag_Label, i_E_Port_Label, i_E_Port_TextField, totalCount_Label, totalCount_TextField, totalWT_Label, totalWT_TextField, trafMode_ComboBox, trafMode_Label, voyageName_TextField});

        dialog_Button3.setText("确定");

        dialog_Button4.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dialog_Button3)
                        .addGap(18, 18, 18)
                        .addComponent(dialog_Button4)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialog_Button4)
                    .addComponent(dialog_Button3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JLabel billNO_Label;
    private javax.swing.JTextField billNO_TextField;
    private javax.swing.JLabel destinationPort_Label;
    private javax.swing.JTextField destinationPort_TextField;
    private javax.swing.JButton dialog_Button3;
    private javax.swing.JButton dialog_Button4;
    private javax.swing.JLabel i_E_Date_Label;
    private javax.swing.JTextField i_E_Date_mp;
    private javax.swing.JComboBox i_E_Flag_ComboBox;
    private javax.swing.JLabel i_E_Flag_Label;
    private javax.swing.JLabel i_E_Port_Label;
    private javax.swing.JTextField i_E_Port_TextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel totalCount_Label;
    private javax.swing.JTextField totalCount_TextField;
    private javax.swing.JLabel totalWT_Label;
    private javax.swing.JTextField totalWT_TextField;
    private javax.swing.JComboBox trafMode_ComboBox;
    private javax.swing.JLabel trafMode_Label;
    private javax.swing.JLabel voyageName_Label;
    private javax.swing.JTextField voyageName_TextField;
    // End of variables declaration
}
