/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xgs.zwy.ui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * 
 * @author n-194
 */
public class CopyOfMainWindows extends javax.swing.JFrame implements ActionListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5517862367149832219L;
	/**
	 * Creates new form MainWindows
	 */
	public CopyOfMainWindows() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		panel = new javax.swing.JPanel();
		
		CardLayout cardLayout = new CardLayout();
		panel.add("全局配置", excel2XmlBtn);
		inputLable = new javax.swing.JLabel();
		outputLable = new javax.swing.JLabel();
		inputPath = new javax.swing.JTextField();
		outputPath = new javax.swing.JTextField();
		inputFileBtn = new javax.swing.JButton();
		outputFileBtn = new javax.swing.JButton();
		excel2XmlBtn = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenu3 = new javax.swing.JMenu();
		jMenu5 = new javax.swing.JMenu();
		jMenu6 = new javax.swing.JMenu();
		jfc = new JFileChooser();// 文件选择器
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("中外运空运");
		setLocationRelativeTo(null); 
		panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		inputLable.setText("导入文件位置：");

		outputLable.setText("导出文件位置：");

		inputPath.setEditable(false);
		outputPath.setEditable(false);
		inputFileBtn.setText("选择导入文件");

		outputFileBtn.setText("选择导出目录");

		excel2XmlBtn.setText("转换");
		inputFileBtn.addActionListener(this);
		outputFileBtn.addActionListener(this);
		excel2XmlBtn.addActionListener(this);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				panel);
		panel.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																excel2XmlBtn)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								outputLable,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								102,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								inputLable,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								102,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								inputPath)
																						.addComponent(
																								outputPath,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								265,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																inputFileBtn)
														.addComponent(
																outputFileBtn))
										.addContainerGap(28, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(31, 31, 31)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																inputLable,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																inputPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																inputFileBtn))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																outputLable,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																outputPath,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																outputFileBtn))
										.addGap(18, 18, 18)
										.addComponent(excel2XmlBtn)
										.addContainerGap(40, Short.MAX_VALUE)));

		jMenu1.setText("文件");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("编辑");
		jMenuBar1.add(jMenu2);

		jMenu3.setText("视图");
		jMenuBar1.add(jMenu3);

		jMenu5.setText("导航");
		jMenuBar1.add(jMenu5);

		jMenu6.setText("配置");
		jMenuBar1.add(jMenu6);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(panel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(83, 83, 83)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addComponent(panel,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(27, Short.MAX_VALUE)));

		pack();
		setVisible(true);
	}// </editor-fold>

	
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CopyOfMainWindows.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CopyOfMainWindows.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CopyOfMainWindows.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CopyOfMainWindows.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginWindows();
			}
		});
	}

	private javax.swing.JButton inputFileBtn;
	private javax.swing.JButton outputFileBtn;
	private javax.swing.JButton excel2XmlBtn;
	private javax.swing.JLabel inputLable;
	private javax.swing.JLabel outputLable;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel panel;
	private javax.swing.JTextField inputPath;
	private javax.swing.JTextField outputPath;
	private JFileChooser jfc = new JFileChooser();
	

	@Override
	public void actionPerformed(ActionEvent e) {
		if (e.getSource().equals(inputFileBtn)) {// 判断触发方法的按钮是哪个
			jfc.setFileSelectionMode(0);// 设定只能选择到文件夹
			int state = jfc.showOpenDialog(panel);// 此句是打开文件选择器界面的触发语句
			if (state == 1) {
				inputPath.setText("");
				return;// 撤销则返回
			} else {
				File f = jfc.getSelectedFile();// f为选择到的目录
				inputPath.setText(f.getAbsolutePath());
			}
		}
		if (e.getSource().equals(outputFileBtn)) {// 判断触发方法的按钮是哪个
			jfc.setFileSelectionMode(1);// 设定只能选择到文件夹
			int state = jfc.showOpenDialog(panel);// 此句是打开文件选择器界面的触发语句
			if (state == 1) {
				outputPath.setText("");
				return;// 撤销则返回
			} else {
				File f = jfc.getSelectedFile();// f为选择到的目录
				outputPath.setText(f.getAbsolutePath());
			}
		}
		if (e.getSource().equals(excel2XmlBtn)) {// 判断触发方法的按钮是哪个

			String input = inputPath.getText();
			String output = outputPath.getText();
			if (input == null || input.trim().length() == 0) {
				JOptionPane.showMessageDialog(null, "请选择要转换的文件！", "提示信息！",
						JOptionPane.ERROR_MESSAGE);
				return;
			}
			if (output == null || output.trim().length() == 0) {
				JOptionPane.showMessageDialog(null, "请选择输出的文件目录", "提示信息！",
						JOptionPane.ERROR_MESSAGE);
				return;
			}
			try {
//				new CDHeadDialog(input.trim(), output.trim());
			} catch (Exception ex) {
				JOptionPane.showMessageDialog(null, ex.getMessage(),
						"对不起，出错了！", JOptionPane.ERROR_MESSAGE);
				ex.printStackTrace();
			}

		}
	}
	
}
