/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xgs.zwy.ui.cdHeadEntry;

/**
 *
 * @author n-194
 */
public class CDEntryHeadPanel extends javax.swing.JPanel {

    /**
     * Creates new form CDEntryHeadInfoPanel
     */
    public CDEntryHeadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        cdHeadPanel = new javax.swing.JPanel();
        billNOLabel = new javax.swing.JLabel();
        billNOTextField = new javax.swing.JTextField();
        voyageNOLabel = new javax.swing.JLabel();
        voyageNOTextField = new javax.swing.JTextField();
        i_E_DateLabel = new javax.swing.JLabel();
        i_E_DateTextField = new javax.swing.JTextField();
        i_E_FlagLabel = new javax.swing.JLabel();
        i_E_FlagTextField = new javax.swing.JTextField();
        totalCountLabel = new javax.swing.JLabel();
        totalCountTextField = new javax.swing.JTextField();
        totalWTLabel = new javax.swing.JLabel();
        totalWTTextField = new javax.swing.JTextField();
        i_E_PortLabel = new javax.swing.JLabel();
        i_E_PortTextField = new javax.swing.JTextField();
        destinationPortLabel = new javax.swing.JLabel();
        destinationPortTextField = new javax.swing.JTextField();
        trafModeLabel = new javax.swing.JLabel();
        trafModeTextField = new javax.swing.JTextField();
        importTimeLabel = new javax.swing.JLabel();
        importTimeTextField = new javax.swing.JTextField();
        cdhEntryHeadPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cdEntryTable = new javax.swing.JTable();
        excel2TxtBnt = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        billNO_searchLabel = new javax.swing.JLabel();
        billNO_searchTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setAutoscrolls(true);

        cdHeadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "主单表头"));
        cdHeadPanel.setToolTipText("");
        cdHeadPanel.setName(""); // NOI18N

        billNOLabel.setText("总运单号：");

        billNOTextField.setEditable(false);
        billNOTextField.setText("jTextField1");

        voyageNOLabel.setText("运输工具名称：");

        voyageNOTextField.setEditable(false);
        voyageNOTextField.setText("jTextField1");

        i_E_DateLabel.setText("进出口日期：");

        i_E_DateTextField.setEditable(false);
        i_E_DateTextField.setText("jTextField1");

        i_E_FlagLabel.setText("进出口标志：");

        i_E_FlagTextField.setEditable(false);
        i_E_FlagTextField.setText("jTextField1");

        totalCountLabel.setText("主单件数：");

        totalCountTextField.setEditable(false);
        totalCountTextField.setText("jTextField1");

        totalWTLabel.setText("主单重量：");

        totalWTTextField.setEditable(false);
        totalWTTextField.setText("jTextField1");

        i_E_PortLabel.setText("进出口岸代码：");

        i_E_PortTextField.setEditable(false);
        i_E_PortTextField.setText("jTextField1");

        destinationPortLabel.setText("起运港/抵运港：");

        destinationPortTextField.setEditable(false);
        destinationPortTextField.setText("jTextField1");

        trafModeLabel.setText("运输方式：");

        trafModeTextField.setEditable(false);
        trafModeTextField.setText("jTextField1");

        importTimeLabel.setText("导入时间：");

        importTimeTextField.setEditable(false);
        importTimeTextField.setText("jTextField1");

        javax.swing.GroupLayout cdHeadPanelLayout = new javax.swing.GroupLayout(cdHeadPanel);
        cdHeadPanel.setLayout(cdHeadPanelLayout);
        cdHeadPanelLayout.setHorizontalGroup(
            cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdHeadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalWTLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_FlagLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(billNOLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importTimeTextField)
                    .addComponent(totalWTTextField)
                    .addComponent(i_E_FlagTextField)
                    .addComponent(billNOTextField))
                .addGap(26, 26, 26)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationPortLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_PortLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voyageNOLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_E_PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voyageNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trafModeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalCountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_DateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trafModeTextField)
                    .addComponent(totalCountTextField)
                    .addComponent(i_E_DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cdHeadPanelLayout.setVerticalGroup(
            cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdHeadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billNOLabel)
                    .addComponent(billNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voyageNOLabel)
                    .addComponent(voyageNOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i_E_DateLabel)
                    .addComponent(i_E_DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_E_FlagLabel)
                    .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(i_E_FlagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(i_E_PortLabel)
                        .addComponent(i_E_PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalCountLabel)
                        .addComponent(totalCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalWTLabel)
                    .addComponent(totalWTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationPortLabel)
                    .addComponent(destinationPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trafModeLabel)
                    .addComponent(trafModeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cdHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importTimeLabel)
                    .addComponent(importTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cdhEntryHeadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "分单数据"));

        cdEntryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "分运单号", "英文货物名称", "中文货物名称", "商品代码", "商品规格型号", "数量", "件数", "重量", "申报总价", "币制", "收(进)/发(出)件人", "发(进)/收(出)件人", "发件人国别(进)/目的国(出)", "发件人城市", "报关类别", "经营单位编码", "经营单位名称"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cdEntryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(cdEntryTable);

        excel2TxtBnt.setText("转换");

        javax.swing.GroupLayout cdhEntryHeadPanelLayout = new javax.swing.GroupLayout(cdhEntryHeadPanel);
        cdhEntryHeadPanel.setLayout(cdhEntryHeadPanelLayout);
        cdhEntryHeadPanelLayout.setHorizontalGroup(
            cdhEntryHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cdhEntryHeadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excel2TxtBnt)
                .addGap(27, 27, 27))
        );
        cdhEntryHeadPanelLayout.setVerticalGroup(
            cdhEntryHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cdhEntryHeadPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(excel2TxtBnt)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "查询面板"));

        billNO_searchLabel.setText("总运单号：");

        billNO_searchTextField.setText("jTextField1");

        jLabel2.setText("分运单号：");

        jTextField2.setText("jTextField2");

        searchButton.setText("查询");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billNO_searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billNO_searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(searchButton)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billNO_searchLabel)
                    .addComponent(billNO_searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cdHeadPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cdhEntryHeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cdHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cdhEntryHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JLabel billNOLabel;
    private javax.swing.JTextField billNOTextField;
    private javax.swing.JLabel billNO_searchLabel;
    private javax.swing.JTextField billNO_searchTextField;
    private javax.swing.JTable cdEntryTable;
    private javax.swing.JPanel cdHeadPanel;
    private javax.swing.JPanel cdhEntryHeadPanel;
    private javax.swing.JLabel destinationPortLabel;
    private javax.swing.JTextField destinationPortTextField;
    private javax.swing.JButton excel2TxtBnt;
    private javax.swing.JLabel i_E_DateLabel;
    private javax.swing.JTextField i_E_DateTextField;
    private javax.swing.JLabel i_E_FlagLabel;
    private javax.swing.JTextField i_E_FlagTextField;
    private javax.swing.JLabel i_E_PortLabel;
    private javax.swing.JTextField i_E_PortTextField;
    private javax.swing.JLabel importTimeLabel;
    private javax.swing.JTextField importTimeTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel totalCountLabel;
    private javax.swing.JTextField totalCountTextField;
    private javax.swing.JLabel totalWTLabel;
    private javax.swing.JTextField totalWTTextField;
    private javax.swing.JLabel trafModeLabel;
    private javax.swing.JTextField trafModeTextField;
    private javax.swing.JLabel voyageNOLabel;
    private javax.swing.JTextField voyageNOTextField;
    // End of variables declaration
}
