  
        /*
         * To change this template, choose Tools | Templates
         * and open the template in the editor.
         */
        package com.xgs.zwy.ui.main;

import javax.swing.JOptionPane;

import com.xgs.zwy.base.ThreadLocalVariable;
import com.xgs.zwy.domain.SystemSetting;
import com.xgs.zwy.ui.JProgressBarTest;
import com.xgs.zwy.ui.LoginWindows;
import com.xgs.zwy.ui.SystemSettingPanel;
import com.xgs.zwy.ui.TransformPanel;
import com.xgs.zwy.ui.cdHead.CDheadList;
import com.xgs.zwy.ui.cdHeadEntry.CDEntryHeadPanel;
import com.xgs.zwy.util.PropertiesUtil;

        /**
         *
         * @author n-194
         */
        public class MainFrame extends javax.swing.JFrame {

            /**
			 * 
			 */
			private static final long serialVersionUID = 2878897161305749499L;
			/**
             * Creates new form mainFrame
             */
            public MainFrame() {
                initComponents();
            }

            /**
             * This method is called from within the constructor to initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is always
             * regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">
            private void initComponents() {

                tabbedPane1 = new javax.swing.JTabbedPane();
                systemSettingPanel=new SystemSettingPanel();
                transformPanel = new TransformPanel();
                tabbedPane1.addTab("文件转换", transformPanel);
//                tabbedPane1.addTab("全局设置",systemSettingPanel );
                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                showPanel();
                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>
        	private  void showPanel(){
//    			SystemSetting systemSetting= PropertiesUtil.getSystemSetting();
//    			if(systemSetting==null){
//    				tabbedPane1.setSelectedComponent(systemSettingPanel);
//    			}else{
//    				ThreadLocalVariable.setSystemSetting(systemSetting);
//    				systemSettingPanel.initValue(systemSetting);
//    				tabbedPane1.setSelectedIndex(0);
//    			}
    			
    	}
            /**
             * @param args the command line arguments
             */
            public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                JProgressBarTest jProgressBarTest = new JProgressBarTest();
        		jProgressBarTest.setVisible(true);
        		try {
        			PropertiesUtil.initSystemSetting();
        		} catch (Exception e) {
        			e.printStackTrace();
        			int status = JOptionPane.showOptionDialog(null,"对不起系统启动错误！","确认提示",JOptionPane.YES_OPTION,JOptionPane.ERROR_MESSAGE,null,new String[]{" 确定 "},null);
        			if(status!=999999){
        				System.exit(ERROR);
        			}
        		}
        		jProgressBarTest.dispose();
        		new LoginWindows();
            }
            // Variables declaration - do not modify
            private javax.swing.JTabbedPane tabbedPane1;
            private SystemSettingPanel systemSettingPanel;
            private TransformPanel transformPanel;
            // End of variables declaration
        }
